winzou_state_machine:
  sylius_payment:
    callbacks:
      after:
        sylius_invoicing_plugin_payment_complete_producer:
          on: ['complete']
          do: ['@zambodaniel_sylius_billingo_plugin.event_producer.order_payment_paid', '__invoke']
          args: ['object']